export const canvasDimension = { x: 50, y: 50 }

export const initialZoomLevel = 15

export const gridIsInitiallyVisible = true

export const defaultColor = "gray-800"

// TODO: there's a whitelist of colors in tailwind.config.js
export const colors = [
  "gray-800",
  "yellow-400",
  "pink-500",
  "red-400",
  "orange-400",
  "rose-600",
  "indigo-500",
  "blue-400",
  "sky-600",
  "cyan-600",
  "teal-400",
  "green-400",
  "emerald-400",
  "fuchsia-500",
  "purple-600",
  "violet-500",
]

export const emptyTile = { symbol: " ", id: 32, group: "hole figures" };

// TODO: missing, middle lines, and a cross. Also negatives of double rounded corners (Smith tiles)
export const tilesMap = [
  emptyTile,
  { symbol: "š", id: 353, group: "hole figures" },
  { symbol: "í", id: 237, group: "hole figures" },
  { symbol: "ë", id: 235, group: "hole figures" },
  { symbol: "›", id: 8250, group: "diagonals" },
  { symbol: "œ", id: 339, group: "diagonals" },
  { symbol: "", id: 157, group: "diagonals" },
  { symbol: "", id: 158, group: "diagonals" },
  { symbol: "Ù", id: 217, group: "semi circles" },
  { symbol: "Û", id: 219, group: "semi circles" },
  { symbol: "Ú", id: 218, group: "semi circles" },
  { symbol: "Ü", id: 220, group: "semi circles" },
  { symbol: "á", id: 225, group: "two half circles" },
  { symbol: "â", id: 226, group: "two half circles" },
  { id: 211, symbol: "Ó", group: "dots in diagonal" },
  { id: 212, symbol: "Ô", group: "dots in diagonal" },
  { id: 177, symbol: "±", group: "mirrored piramid" },
  { id: 178, symbol: "²", group: "mirrored piramid" },
  { id: 193, symbol: "Á", group: "diagonal corners" },
  { id: 194, symbol: "Â", group: "diagonal corners" },
  { symbol: "", id: 127, group: "arrows" },
  { symbol: "", id: 128, group: "arrows" },
  { symbol: "", id: 129, group: "arrows" },
  { symbol: "‚", id: 130, group: "arrows" },
  { symbol: "ê", id: 234, group: undefined },
  { symbol: "y", id: 121, group: undefined },
  { symbol: "z", id: 122, group: undefined },
  { symbol: "x", id: 120, group: undefined },
  { symbol: "L", id: 76, group: "squared C" },
  { symbol: "N", id: 78, group: "squared C" },
  { symbol: "M", id: 77, group: "squared C" },
  { symbol: "O", id: 79, group: "squared C" },
  { symbol: "b", id: 98, group: "base lines" },
  { symbol: "c", id: 99, group: "base lines" },
  { symbol: "e", id: 101, group: "base lines" },
  { symbol: "d", id: 100, group: "base lines" },
  { symbol: "\\", id: 92, group: "archs" },
  { symbol: "]", id: 93, group: "archs" },
  { symbol: "Z", id: 90, group: "archs" },
  { symbol: "[", id: 91, group: "archs" },
  { symbol: ":", id: 58, group: undefined },
  { symbol: ";", id: 59, group: undefined },
  { symbol: "8", id: 56, group: undefined },
  { symbol: "9", id: 57, group: undefined },
  { symbol: "§", id: 167, group: "squared quarters" },
  { symbol: "¨", id: 168, group: "squared quarters" },
  { symbol: "©", id: 169, group: "squared quarters" },
  { symbol: "ª", id: 170, group: "squared quarters" },
  { symbol: "j", id: 106, group: "little rounded corners" },
  { symbol: "k", id: 107, group: "little rounded corners" },
  { symbol: "l", id: 108, group: "little rounded corners" },
  { symbol: "m", id: 109, group: "little rounded corners" },
  { id: 207, symbol: "Ï", group: "rounded corners" },
  { id: 208, symbol: "Ð", group: "rounded corners" },
  { id: 209, symbol: "Ñ", group: "rounded corners" },
  { id: 210, symbol: "Ò", group: "rounded corners" },
  { symbol: "–", id: 8211, group: "circle quarters" },
  { symbol: "—", id: 8212, group: "circle quarters" },
  { symbol: "˜", id: 732, group: "circle quarters" },
  { symbol: "™", id: 8482, group: "circle quarters" },
  { symbol: "D", id: 68, group: "half rings" },
  { symbol: "F", id: 70, group: "half rings" },
  { symbol: "E", id: 69, group: "half rings" },
  { symbol: "G", id: 71, group: "half rings" },
  { symbol: "H", id: 72, group: "cheese" },
  { symbol: "J", id: 74, group: "cheese" },
  { symbol: "I", id: 73, group: "cheese" },
  { symbol: "K", id: 75, group: "cheese" },
  { symbol: "P", id: 80, group: "roadway" },
  { symbol: "Q", id: 81, group: "roadway" },
  { symbol: "R", id: 82, group: "roadway" },
  { symbol: "S", id: 83, group: "roadway" },
  { symbol: "@", id: 64, group: "rounded roadways" },
  { symbol: "A", id: 65, group: "rounded roadways" },
  { symbol: "B", id: 66, group: "rounded roadways" },
  { symbol: "C", id: 67, group: "rounded roadways" },
  { symbol: "n", id: 110, group: "double corner dots" },
  { symbol: "o", id: 111, group: "double corner dots" },
  { symbol: "p", id: 112, group: "double corner dots" },
  { symbol: "q", id: 113, group: "double corner dots" },
  { symbol: "%", id: 37, group: "miscellaneous" },
  { symbol: "&", id: 38, group: "miscellaneous" },
  { symbol: "«", id: 171, group: "miscellaneous" },
  { symbol: "¬", id: 172, group: "miscellaneous" },
  { symbol: "~", id: 126, group: "T bridges" },
  { symbol: "}", id: 125, group: "T bridges" },
  { symbol: "{", id: 123, group: "T bridges" },
  { symbol: "|", id: 124, group: "T bridges" },
  { id: 45, symbol: "-", group: "horseshoes" },
  { id: 44, symbol: ",", group: "horseshoes" },
  { id: 46, symbol: ".", group: "horseshoes" },
  { id: 43, symbol: "+", group: "horseshoes" },
  { id: 33, symbol: "!", group: "archs with dot" },
  { id: 34, symbol: '"', group: "archs with dot" },
  { id: 35, symbol: "#", group: "archs with dot" },
  { id: 36, symbol: "$", group: "archs with dot" },
  { id: 48, symbol: "0", group: "contrast corner curves" },
  { id: 49, symbol: "1", group: "contrast corner curves" },
  { id: 50, symbol: "2", group: "contrast corner curves" },
  { id: 51, symbol: "3", group: "contrast corner curves" },
  { id: 40, symbol: "(", group: "punctuation" },
  { id: 41, symbol: ")", group: "punctuation" },
  { id: 39, symbol: "'", group: "punctuation" },
  { id: 42, symbol: "*", group: "punctuation" },
  { id: 47, symbol: "/", group: "punctuation" },
  { id: 55, symbol: "7", group: "numbers" },
  { id: 193, symbol: "Á", group: "letters" },
  { id: 194, symbol: "Â", group: "letters" },
  { id: 163, symbol: "£", group: "tetris arrow (diagonal)" },
  { id: 164, symbol: "¤", group: "tetris arrow (diagonal)" },
  { id: 165, symbol: "¥", group: "tetris arrow (diagonal)" },
  { id: 166, symbol: "¦", group: "tetris arrow (diagonal)" },
  { id: 179, symbol: "³", group: "Ks" },
  { id: 180, symbol: "´", group: "Ks" },
  { id: 181, symbol: "µ", group: "Ks" },
  { id: 182, symbol: "¶", group: "Ks" },
  { id: 189, symbol: "½", group: "bold pointers" },
  { id: 190, symbol: "¾", group: "bold pointers" },
  { id: 191, symbol: "¿", group: "bold pointers" },
  { id: 192, symbol: "À", group: "bold pointers" },
  { id: 195, symbol: "Ã", group: "letters" },
  { id: 196, symbol: "Ä", group: "letters" },
  { id: 197, symbol: "Å", group: "letters" },
  { id: 198, symbol: "Æ", group: "letters" },
  { id: 174, symbol: "®", group: "piramids (TODO: rotate this one)" },
  { id: 175, symbol: "¯", group: "piramids (TODO: rotate this one)" },
  { id: 176, symbol: "°", group: "piramids (TODO: rotate this one)" },
  { id: 8225, symbol: "‡", group: "piramid corners" },
  { id: 221, symbol: "Ý", group: "clouds" },
  { id: 222, symbol: "Þ", group: "clouds" },
  { id: 223, symbol: "ß", group: "clouds" },
  { id: 224, symbol: "à", group: "clouds" },
  { id: 402, symbol: "ƒ", group: "confeti" },
  { id: 8222, symbol: "„", group: "confeti" },
  { id: 8230, symbol: "…", group: "confeti" },
  { id: 8224, symbol: "†", group: "confeti" },
  { id: 52, symbol: "4", group: "x" },
  { id: 53, symbol: "5", group: "x" },
  { id: 54, symbol: "6", group: "x" },
  { id: 55, symbol: "7", group: "x" },
  { id: 84, symbol: "T", group: "x" },
  { id: 85, symbol: "U", group: "x" },
  { id: 86, symbol: "V", group: "x" },
  { id: 87, symbol: "W", group: "x" },
  { id: 159, symbol: "Ÿ", group: "bold lines" },
  { id: 160, symbol: " ", group: "bold lines" },
  { id: 161, symbol: "¡", group: "bold lines" },
  { id: 162, symbol: "¢", group: "bold lines" },
  { id: 118, symbol: "v", group: "x" },
  { id: 119, symbol: "w", group: "x" },
  { id: 183, symbol: "·", group: "x" },
  { id: 184, symbol: "¸", group: "x" },
]




